name = ('это моя строка')
print(name[0])
print(name[-1])
print(name[2:5])
print(name[::-1])
d=len(name)
print(d)
print('это новая строка '+ 'это моя строка')
name2 = (' это новая строка')
print(name + name2)